package Utilities;

/** Holds the settings that can be set by the user
 * 
 * @author Matt Pedersen
 *
 */
public class Settings {
	/** Directory where the Espresso include (source) files are located */
	public static String includeDir = "Include";
	/** Determine if the code generated is for the EVM or the JVM.
	 * If code is generated for the JVM, the Main method will take in
	 * an array of Strings; otherwise it will not take any parameters
	 */
	public static boolean generateEVMCode = false; // are we generating code for the EVM?
	/** The extension of the Jasmin files generated by the compiler.
	 * The default is '.j' - this can be changed to '.rj' by the -ref 
	 * command line option.
	 */
	public static String fileExt = ".j"; // command line -ref changes this
}
